import os
from windowClasses import *
from datastorage import *
import tkFileDialog
from Tkinter import *

# NOTE: This program expects the directory containing log files to all have the naming scheme generated by the TLOPO launcher. Expect it to crash if the naming scheme is not followed.
Tk().withdraw()

logM = logManager()
test = bootWindow(logM)

